### ISSUE TITLE
Adding Robot Models

### ISSUE THREAD

**Issue by jarrettHoltz** [ut-amrl/ut_multirobot_sim#2]
The simulator needs to support different dynamics models for different robots.
A config reader file can be used to set both the model to use, and the parameters of the model.  
The actual update loop of the simulator will need to handle different messages types (ackermann vs diff drive, etc) appropriately.

**Comment by kylevedder** [comment]
As part of this, the simulator needs different topics to handle the different message types. For Turtlebot2 support, it needs to subscribe to `/mobile_base/commands/velocity` of type `geometry_msgs/Twist`.

**Comment by jarrettHoltz** [comment]
If you look at the way the ackermann_model is setup, the motion model that is being used determines the topics being subscribed to (and the message  types). The answer is probably just to add a drive/motion model class for the turtlebots.

**Comment by kylevedder** [comment]
That's true; I forgot to include a request to update the README in your PR for the pulled out model.
