### ISSUE TITLE
Build fails when compiling with Clang due to Eigen Macro

### ISSUE THREAD

**Issue by jarrettHoltz** [ut-amrl/ut_multirobot_sim#24]
Eigen alignment macro is creating a typedef that Clang thinks is unused. Is this an error on Clang's part, or do we not need this macro inside a struct?

```
/home/travis/build/ut-amrl/f1tenth_simulator/src/simulator/vector_map.cpp:295:5: error: 
      unused typedef 'eigen_aligned_operator_new_marker_type'
      [-Werror,-Wunused-local-typedef]
    EIGEN_MAKE_ALIGNED_OPERATOR_NEW
    ^
/usr/include/eigen3/Eigen/src/Core/util/Memory.h:690:41: note: expanded from
      macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW'
#define EIGEN_MAKE_ALIGNED_OPERATOR_NEW EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF(true)
                                        ^
/usr/include/eigen3/Eigen/src/Core/util/Memory.h:685:20: note: expanded from
      macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF'
      typedef void eigen_aligned_operator_new_marker_type;
                   ^
1 error generated.
```

**Comment by joydeep-b** [comment]
Reference: 
https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html#StructHavingEigenMembers_othersolutions

@jarrettHoltz  Could you try commenting out the macro invocation, and see if the simulator still works?

**Comment by jarrettHoltz** [comment]
> @jarrettHoltz Could you try commenting out the macro invocation, and see if the simulator still works?

It doesn't change anything that I notice. I actually used it with this commented out for awhile because I use Clang as my default compiler.

**Comment by joydeep-b** [comment]
Do you have access to a 32-bit machine, virtual or real and an ARM platform?
If it is fine on those platforms let's remove the macro invocation.

**Comment by jarrettHoltz** [comment]
No I don't have either. Although I could setup vm software and vms if that's what has to be done.

**Comment by joydeep-b** [comment]
Okay, how about doing something different: Add a warning to print in yellow text from CMakelists.txt if it detects a non amd64 architecture, to mention that this may be a problem. And then let's remove the macro, and re-evaluate if it turns out to be an issue later.

**Comment by jarrettHoltz** [comment]
Print added, macro removed, CI passing.
